name: pikaday_datepicker
description: Provides a dart datepicker by wrapping the lightweight pikaday js-library.
version: 3.0.1
author: Stephan Schroeder <simon.void+github@gmail.com>
homepage: https://github.com/simon-void/pikaday_datepicker
environment:
  sdk: '>=2.0.0-dev.69.3 <3.0.0'
dev_dependencies:
  build_runner: ^0.10.0
  build_web_compilers: ^0.4.0