name: pikaday_datepicker
description: Provides an Angular2 datepicker component by wrapping the lightweight pikaday js-library.
version: 0.8.2
author: Stephan Schroeder <simon.void+github@gmail.com>
homepage: https://github.com/simon-void/pikaday_datepicker
environment:
  sdk: '>=1.21.0 <2.0.0'
dependencies:
  angular2: ^2.2.0