name: pikaday_datepicker
description: Provides an Angular2 datepicker component by wrapping the lightweight pikaday js-library.
version: 0.8.6
author: Stephan Schroeder <simon.void+github@gmail.com>
homepage: https://github.com/simon-void/pikaday_datepicker
environment:
  sdk: '>=1.20.0 <2.0.0'
dependencies:
  angular2: ^2.2.0
dev_dependencies:
  browser: ^0.10.0
transformers:
- angular2
#- angular2:
#    platform_directives:
#    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
#    platform_pipes:
#    - 'package:angular2/common.dart#COMMON_PIPES'
#    entry_points: example/main.dart